# Generated by Django 4.2.7 on 2023-12-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetExpenseTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
