# Generated by Django 4.2.7 on 2023-12-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetExpenseTrack', '0002_users_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Expense_created_date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user_id',
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BudgetExpenseTrack.category'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BudgetExpenseTrack.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
